# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='extentaion',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
