# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_person_extentaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
