# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20161202_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='staff_images'),
        ),
    ]
